# 실행에서 제외할 룰 식별자
disabled_rules:
- line_length
- trailing_whitespace
- function_parameter_count
- file_length
- identifier_name
- function_body_length
# 린트 과정에서 무시할 파일 경로
excluded:
- Tabling-iOS/Application/AppDelegate.swift
- Tabling-iOS/Application/SceneDelegate.swift
- Tabling-iOS/View.swift
- Tabling-iOS/ViewController.swift
- Tabling-iOS/ExampleCollectionViewCell.swift
